jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      Python2.7:
        python_version: '2.7'
      Python3.5:
        python_version: '3.5'
      Python3.6:
        python_version: '3.6'
      Python3.7:
        python_version: '3.7'

  variables:
    # Enable fuzzing tests, other expensive tests.
    ZSTD_SLOW_TESTS: '1'

    # Make all compile warnings fatal.
    ZSTD_WARNINGS_AS_ERRORS: '1'

    # More thorough fuzzing coverage.
    HYPOTHESIS_PROFILE: ci

  steps:
  - script: choco install vcpython27 --yes
    displayName: Install VC++ for Python 2.7
    condition: eq(variables['python_version'], '2.7')

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name env python=%PYTHON_VERSION%
    displayName: Create Anaconda environment

  - script: |
      call activate env || exit 1
      call conda install --yes --quiet --name env conda-build pip || exit 1
      call pip install --require-hashes -r ci/requirements.txt || exit 1
    displayName: Install dependencies

  - script: |
      call activate env || exit 1
      call conda build ci/conda || exit 1
      call python ci/copy-conda-package.py || exit 1
    displayName: Build and Test

  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/dist
